# Reference data for the SDC verification gate.
#
# Everything in this file is generated from qmat (https://github.com/Parallel-in-Time/qmat)
# by sdc-notes/tools/gen_reference.py. It is checked in so the Julia test suite has no
# Python dependency; regenerate it if qmat's conventions change.

# Golden coefficient values generated by qmat (Parallel-in-Time/qmat).
# Generated by sdc-notes/tools/gen_reference.py; do not edit by hand.
const QMAT_GOLDEN = [
    (
        M = 4, node_type = :Legendre, quad_type = :Gauss, coll_order = 8,
        nodes = [0.06943184420297371, 0.33000947820757187, 0.6699905217924281, 0.9305681557970262],
        weights = [0.17392742256872673, 0.32607257743127344, 0.3260725774312727, 0.17392742256872715],
        Q = [
            0.08696371128436348 -0.02660418008499879 0.012627462689404723 -0.003555149685795684;
            0.18811811749986806 0.16303628871563652 -0.027880428602470912 0.00673550059453816;
            0.16719192197418872 0.35395300603374397 0.16303628871563652 -0.014190694931141138;
            0.1774825722545225 0.31344511474186854 0.35267675751627175 0.08696371128436353
        ],
        QDelta = Dict(
            :BE => [
                0.06943184420297371 0.0 0.0 0.0;
                0.06943184420297371 0.26057763400459816 0.0 0.0;
                0.06943184420297371 0.26057763400459816 0.33998104358485626 0.0;
                0.06943184420297371 0.26057763400459816 0.33998104358485626 0.2605776340045981
            ],
            :FE => [
                0.0 0.0 0.0 0.0;
                0.26057763400459816 0.0 0.0 0.0;
                0.26057763400459816 0.33998104358485626 0.0 0.0;
                0.26057763400459816 0.33998104358485626 0.2605776340045981 0.0
            ],
            :Trapezoid => [
                0.03471592210148686 0.0 0.0 0.0;
                0.16500473910378594 0.13028881700229908 0.0 0.0;
                0.16500473910378594 0.30027933879472724 0.16999052179242813 0.0;
                0.16500473910378594 0.30027933879472724 0.3002793387947272 0.13028881700229905
            ],
            :LU => [
                0.08696371128436348 0.0 0.0 0.0;
                0.18811811749986806 0.22058590569153172 0.0 0.0;
                0.16719192197418872 0.40510082315500057 0.24012534929291057 0.0;
                0.1774825722545225 0.3677410761776488 0.4189232694951132 0.12922212642709544
            ],
            :Picard => [
                0.0 0.0 0.0 0.0;
                0.0 0.0 0.0 0.0;
                0.0 0.0 0.0 0.0;
                0.0 0.0 0.0 0.0
            ],
            :BEpar => [
                0.06943184420297371 0.0 0.0 0.0;
                0.0 0.33000947820757187 0.0 0.0;
                0.0 0.0 0.6699905217924281 0.0;
                0.0 0.0 0.0 0.9305681557970262
            ],
            :MIN_SR_NS => [
                0.01735796105074343 0.0 0.0 0.0;
                0.0 0.08250236955189297 0.0 0.0;
                0.0 0.0 0.16749763044810703 0.0;
                0.0 0.0 0.0 0.23264203894925656
            ],
        ),
    ),
    (
        M = 2, node_type = :Legendre, quad_type = :RadauLeft, coll_order = 3,
        nodes = [0.0, 0.6666666666666666],
        weights = [0.24999999999999992, 0.7500000000000001],
        Q = [
            0.0 0.0;
            0.3333333333333333 0.3333333333333333
        ],
        QDelta = Dict(
            :BE => [
                0.0 0.0;
                0.0 0.6666666666666666
            ],
            :FE => [
                0.0 0.0;
                0.6666666666666666 0.0
            ],
            :Trapezoid => [
                0.0 0.0;
                0.3333333333333333 0.3333333333333333
            ],
            :LU => [
                0.0 0.0;
                0.3333333333333333 0.3333333333333333
            ],
            :Picard => [
                0.0 0.0;
                0.0 0.0
            ],
            :BEpar => [
                0.0 0.0;
                0.0 0.6666666666666666
            ],
            :MIN_SR_NS => [
                0.0 0.0;
                0.0 0.3333333333333333
            ],
        ),
    ),
    (
        M = 3, node_type = :Legendre, quad_type = :RadauRight, coll_order = 5,
        nodes = [0.15505102572168222, 0.6449489742783178, 1.0],
        weights = [0.3764030627004673, 0.5124858261884215, 0.1111111111111112],
        Q = [
            0.19681547722366047 -0.0655354258501984 0.02377097434822016;
            0.3944243147390873 0.29207341166522843 -0.04154875212599792;
            0.3764030627004673 0.5124858261884215 0.1111111111111112
        ],
        QDelta = Dict(
            :BE => [
                0.15505102572168222 0.0 0.0;
                0.15505102572168222 0.48989794855663554 0.0;
                0.15505102572168222 0.48989794855663554 0.35505102572168223
            ],
            :FE => [
                0.0 0.0 0.0;
                0.48989794855663554 0.0 0.0;
                0.48989794855663554 0.35505102572168223 0.0
            ],
            :Trapezoid => [
                0.07752551286084111 0.0 0.0;
                0.3224744871391589 0.24494897427831777 0.0;
                0.3224744871391589 0.4224744871391589 0.17752551286084112
            ],
            :LU => [
                0.19681547722366047 0.0 0.0;
                0.3944243147390873 0.42340843570261305 0.0;
                0.3764030627004673 0.6378201512799474 0.20000000000000007
            ],
            :Picard => [
                0.0 0.0 0.0;
                0.0 0.0 0.0;
                0.0 0.0 0.0
            ],
            :BEpar => [
                0.15505102572168222 0.0 0.0;
                0.0 0.6449489742783178 0.0;
                0.0 0.0 1.0
            ],
            :MIN_SR_NS => [
                0.05168367524056074 0.0 0.0;
                0.0 0.2149829914261059 0.0;
                0.0 0.0 0.3333333333333333
            ],
        ),
    ),
    (
        M = 3, node_type = :Legendre, quad_type = :Lobatto, coll_order = 4,
        nodes = [0.0, 0.5, 1.0],
        weights = [0.16666666666666657, 0.6666666666666666, 0.1666666666666667],
        Q = [
            0.0 0.0 0.0;
            0.20833333333333334 0.33333333333333337 -0.041666666666666664;
            0.16666666666666657 0.6666666666666666 0.1666666666666667
        ],
        QDelta = Dict(
            :BE => [
                0.0 0.0 0.0;
                0.0 0.5 0.0;
                0.0 0.5 0.5
            ],
            :FE => [
                0.0 0.0 0.0;
                0.5 0.0 0.0;
                0.5 0.5 0.0
            ],
            :Trapezoid => [
                0.0 0.0 0.0;
                0.25 0.25 0.0;
                0.25 0.5 0.25
            ],
            :LU => [
                0.0 0.0 0.0;
                0.20833333333333334 0.33333333333333337 0.0;
                0.16666666666666657 0.6666666666666666 0.25
            ],
            :Picard => [
                0.0 0.0 0.0;
                0.0 0.0 0.0;
                0.0 0.0 0.0
            ],
            :BEpar => [
                0.0 0.0 0.0;
                0.0 0.5 0.0;
                0.0 0.0 1.0
            ],
            :MIN_SR_NS => [
                0.0 0.0 0.0;
                0.0 0.16666666666666666 0.0;
                0.0 0.0 0.3333333333333333
            ],
        ),
    ),
    (
        M = 4, node_type = :Equidistant, quad_type = :RadauLeft, coll_order = 4,
        nodes = [0.0, 0.25, 0.5, 0.75],
        weights = [-2.7755575615628914e-16, 0.6666666666666673, -0.3333333333333342, 0.6666666666666671],
        Q = [
            0.0 0.0 0.0 0.0;
            0.09374999999999997 0.19791666666666669 -0.052083333333333336 0.010416666666666668;
            0.08333333333333331 0.33333333333333337 0.08333333333333336 6.938893903907228e-18;
            0.09374999999999994 0.28125000000000006 0.28124999999999994 0.09375
        ],
        QDelta = Dict(
            :BE => [
                0.0 0.0 0.0 0.0;
                0.0 0.25 0.0 0.0;
                0.0 0.25 0.25 0.0;
                0.0 0.25 0.25 0.25
            ],
            :FE => [
                0.0 0.0 0.0 0.0;
                0.25 0.0 0.0 0.0;
                0.25 0.25 0.0 0.0;
                0.25 0.25 0.25 0.0
            ],
            :Trapezoid => [
                0.0 0.0 0.0 0.0;
                0.125 0.125 0.0 0.0;
                0.125 0.25 0.125 0.0;
                0.125 0.25 0.25 0.125
            ],
            :LU => [
                0.0 0.0 0.0 0.0;
                0.09374999999999997 0.19791666666666669 0.0 0.0;
                0.08333333333333331 0.33333333333333337 0.1710526315789474 0.0;
                0.09374999999999994 0.28125000000000006 0.3552631578947368 0.11538461538461536
            ],
            :Picard => [
                0.0 0.0 0.0 0.0;
                0.0 0.0 0.0 0.0;
                0.0 0.0 0.0 0.0;
                0.0 0.0 0.0 0.0
            ],
            :BEpar => [
                0.0 0.0 0.0 0.0;
                0.0 0.25 0.0 0.0;
                0.0 0.0 0.5 0.0;
                0.0 0.0 0.0 0.75
            ],
            :MIN_SR_NS => [
                0.0 0.0 0.0 0.0;
                0.0 0.0625 0.0 0.0;
                0.0 0.0 0.125 0.0;
                0.0 0.0 0.0 0.1875
            ],
        ),
    ),
    (
        M = 3, node_type = :Equidistant, quad_type = :Lobatto, coll_order = 4,
        nodes = [0.0, 0.5, 1.0],
        weights = [0.16666666666666657, 0.6666666666666666, 0.1666666666666667],
        Q = [
            0.0 0.0 0.0;
            0.20833333333333334 0.33333333333333337 -0.041666666666666664;
            0.16666666666666657 0.6666666666666666 0.1666666666666667
        ],
        QDelta = Dict(
            :BE => [
                0.0 0.0 0.0;
                0.0 0.5 0.0;
                0.0 0.5 0.5
            ],
            :FE => [
                0.0 0.0 0.0;
                0.5 0.0 0.0;
                0.5 0.5 0.0
            ],
            :Trapezoid => [
                0.0 0.0 0.0;
                0.25 0.25 0.0;
                0.25 0.5 0.25
            ],
            :LU => [
                0.0 0.0 0.0;
                0.20833333333333334 0.33333333333333337 0.0;
                0.16666666666666657 0.6666666666666666 0.25
            ],
            :Picard => [
                0.0 0.0 0.0;
                0.0 0.0 0.0;
                0.0 0.0 0.0
            ],
            :BEpar => [
                0.0 0.0 0.0;
                0.0 0.5 0.0;
                0.0 0.0 1.0
            ],
            :MIN_SR_NS => [
                0.0 0.0 0.0;
                0.0 0.16666666666666666 0.0;
                0.0 0.0 0.3333333333333333
            ],
        ),
    ),
]

# (M, node_type, quad_type, sweeper, K, step_update, expected_order, is_bonus_case)
# `expected_order` is qmat's `getOrderSDC` prediction, and every row below is one
# whose measured order qmat's own convergence test accepts.
# `is_bonus_case` marks the rows where qmat's hard-coded bonus table predicts a
# higher order than the base rule `alg_order` implements; there our prediction is
# a strict lower bound. See sdc-notes/04-verification.md.
const ORDER_CASES = [
    (2, :Legendre, :Gauss, :BE, 1, :quadrature, 2, false),  # qmat observed 1.995
    (2, :Legendre, :Gauss, :BE, 2, :quadrature, 3, false),  # qmat observed 2.961
    (2, :Legendre, :Gauss, :BE, 3, :quadrature, 4, false),  # qmat observed 3.827
    (2, :Legendre, :Gauss, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (2, :Legendre, :Gauss, :FE, 2, :quadrature, 3, false),  # qmat observed 3.001
    (2, :Legendre, :Gauss, :FE, 3, :quadrature, 4, false),  # qmat observed 4.020
    (2, :Legendre, :Gauss, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.995
    (2, :Legendre, :Gauss, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 3.991
    (2, :Legendre, :Gauss, :Trapezoid, 3, :quadrature, 4, false),  # qmat observed 3.967
    (2, :Legendre, :Gauss, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.992
    (2, :Legendre, :Gauss, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.927
    (2, :Legendre, :Gauss, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.650
    (3, :Legendre, :Gauss, :BE, 1, :quadrature, 2, false),  # qmat observed 1.997
    (3, :Legendre, :Gauss, :BE, 2, :quadrature, 3, false),  # qmat observed 2.977
    (3, :Legendre, :Gauss, :BE, 3, :quadrature, 4, false),  # qmat observed 3.904
    (3, :Legendre, :Gauss, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (3, :Legendre, :Gauss, :FE, 2, :quadrature, 3, false),  # qmat observed 3.001
    (3, :Legendre, :Gauss, :FE, 3, :quadrature, 4, false),  # qmat observed 4.012
    (3, :Legendre, :Gauss, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.996
    (3, :Legendre, :Gauss, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.174
    (3, :Legendre, :Gauss, :Trapezoid, 3, :quadrature, 5, false),  # qmat observed 5.478
    (3, :Legendre, :Gauss, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.991
    (3, :Legendre, :Gauss, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.913
    (3, :Legendre, :Gauss, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.574
    (4, :Legendre, :Gauss, :BE, 1, :quadrature, 2, false),  # qmat observed 1.997
    (4, :Legendre, :Gauss, :BE, 2, :quadrature, 3, false),  # qmat observed 2.984
    (4, :Legendre, :Gauss, :BE, 3, :quadrature, 4, false),  # qmat observed 3.943
    (4, :Legendre, :Gauss, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (4, :Legendre, :Gauss, :FE, 2, :quadrature, 3, false),  # qmat observed 3.003
    (4, :Legendre, :Gauss, :FE, 3, :quadrature, 4, false),  # qmat observed 4.026
    (4, :Legendre, :Gauss, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.997
    (4, :Legendre, :Gauss, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.226
    (4, :Legendre, :Gauss, :Trapezoid, 3, :quadrature, 5, false),  # qmat observed 5.263
    (4, :Legendre, :Gauss, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.991
    (4, :Legendre, :Gauss, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.913
    (4, :Legendre, :Gauss, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.567
    (2, :Legendre, :RadauLeft, :BE, 1, :quadrature, 2, false),  # qmat observed 1.994
    (2, :Legendre, :RadauLeft, :BE, 2, :quadrature, 3, false),  # qmat observed 2.950
    (2, :Legendre, :RadauLeft, :BE, 3, :quadrature, 3, false),  # qmat observed 2.863
    (2, :Legendre, :RadauLeft, :FE, 1, :quadrature, 2, false),  # qmat observed 2.002
    (2, :Legendre, :RadauLeft, :FE, 2, :quadrature, 3, false),  # qmat observed 2.994
    (2, :Legendre, :RadauLeft, :FE, 3, :quadrature, 3, false),  # qmat observed 3.029
    (2, :Legendre, :RadauLeft, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.994
    (2, :Legendre, :RadauLeft, :Trapezoid, 2, :quadrature, 3, false),  # qmat observed 2.994
    (2, :Legendre, :RadauLeft, :Trapezoid, 3, :quadrature, 3, false),  # qmat observed 2.994
    (2, :Legendre, :RadauLeft, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.994
    (2, :Legendre, :RadauLeft, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.950
    (2, :Legendre, :RadauLeft, :BEpar, 3, :quadrature, 3, false),  # qmat observed 2.863
    (3, :Legendre, :RadauLeft, :BE, 1, :quadrature, 2, false),  # qmat observed 1.996
    (3, :Legendre, :RadauLeft, :BE, 2, :quadrature, 3, false),  # qmat observed 2.971
    (3, :Legendre, :RadauLeft, :BE, 3, :quadrature, 4, false),  # qmat observed 3.868
    (3, :Legendre, :RadauLeft, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (3, :Legendre, :RadauLeft, :FE, 2, :quadrature, 3, false),  # qmat observed 3.001
    (3, :Legendre, :RadauLeft, :FE, 3, :quadrature, 4, false),  # qmat observed 4.024
    (3, :Legendre, :RadauLeft, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.996
    (3, :Legendre, :RadauLeft, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.216
    (3, :Legendre, :RadauLeft, :Trapezoid, 3, :quadrature, 5, false),  # qmat observed 4.990
    (3, :Legendre, :RadauLeft, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.991
    (3, :Legendre, :RadauLeft, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.919
    (3, :Legendre, :RadauLeft, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.615
    (4, :Legendre, :RadauLeft, :BE, 1, :quadrature, 2, false),  # qmat observed 1.997
    (4, :Legendre, :RadauLeft, :BE, 2, :quadrature, 3, false),  # qmat observed 2.981
    (4, :Legendre, :RadauLeft, :BE, 3, :quadrature, 4, false),  # qmat observed 3.926
    (4, :Legendre, :RadauLeft, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (4, :Legendre, :RadauLeft, :FE, 2, :quadrature, 3, false),  # qmat observed 3.002
    (4, :Legendre, :RadauLeft, :FE, 3, :quadrature, 4, false),  # qmat observed 4.024
    (4, :Legendre, :RadauLeft, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.997
    (4, :Legendre, :RadauLeft, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.204
    (4, :Legendre, :RadauLeft, :Trapezoid, 3, :quadrature, 5, false),  # qmat observed 5.288
    (4, :Legendre, :RadauLeft, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.991
    (4, :Legendre, :RadauLeft, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.913
    (4, :Legendre, :RadauLeft, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.562
    (2, :Legendre, :RadauRight, :BE, 1, :quadrature, 2, false),  # qmat observed 1.994
    (2, :Legendre, :RadauRight, :BE, 2, :quadrature, 3, false),  # qmat observed 2.948
    (2, :Legendre, :RadauRight, :BE, 3, :quadrature, 3, false),  # qmat observed 3.116
    (2, :Legendre, :RadauRight, :BE, 1, :lastnode, 1, false),  # qmat observed 0.954
    (2, :Legendre, :RadauRight, :BE, 2, :lastnode, 2, false),  # qmat observed 1.987
    (2, :Legendre, :RadauRight, :BE, 3, :lastnode, 3, false),  # qmat observed 3.068
    (2, :Legendre, :RadauRight, :BE, 4, :lastnode, 3, false),  # qmat observed 2.841
    (2, :Legendre, :RadauRight, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (2, :Legendre, :RadauRight, :FE, 2, :quadrature, 3, false),  # qmat observed 2.998
    (2, :Legendre, :RadauRight, :FE, 3, :quadrature, 3, false),  # qmat observed 3.048
    (2, :Legendre, :RadauRight, :FE, 1, :lastnode, 1, false),  # qmat observed 1.046
    (2, :Legendre, :RadauRight, :FE, 2, :lastnode, 2, false),  # qmat observed 2.004
    (2, :Legendre, :RadauRight, :FE, 3, :lastnode, 3, false),  # qmat observed 3.016
    (2, :Legendre, :RadauRight, :FE, 4, :lastnode, 3, false),  # qmat observed 3.055
    (2, :Legendre, :RadauRight, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.994
    (2, :Legendre, :RadauRight, :Trapezoid, 2, :quadrature, 3, false),  # qmat observed 2.981
    (2, :Legendre, :RadauRight, :Trapezoid, 3, :quadrature, 3, false),  # qmat observed 2.996
    (2, :Legendre, :RadauRight, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 1.998
    (2, :Legendre, :RadauRight, :Trapezoid, 2, :lastnode, 3, false),  # qmat observed 2.983
    (2, :Legendre, :RadauRight, :Trapezoid, 3, :lastnode, 3, false),  # qmat observed 2.990
    (2, :Legendre, :RadauRight, :Trapezoid, 4, :lastnode, 3, false),  # qmat observed 2.991
    (2, :Legendre, :RadauRight, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.988
    (2, :Legendre, :RadauRight, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.892
    (2, :Legendre, :RadauRight, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (2, :Legendre, :RadauRight, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.965
    (2, :Legendre, :RadauRight, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.867
    (2, :Legendre, :RadauRight, :BEpar, 4, :lastnode, 3, false),  # qmat observed 3.444
    (3, :Legendre, :RadauRight, :BE, 1, :quadrature, 2, false),  # qmat observed 1.996
    (3, :Legendre, :RadauRight, :BE, 2, :quadrature, 3, false),  # qmat observed 2.970
    (3, :Legendre, :RadauRight, :BE, 3, :quadrature, 4, false),  # qmat observed 3.872
    (3, :Legendre, :RadauRight, :BE, 1, :lastnode, 1, false),  # qmat observed 0.968
    (3, :Legendre, :RadauRight, :BE, 2, :lastnode, 2, false),  # qmat observed 1.994
    (3, :Legendre, :RadauRight, :BE, 3, :lastnode, 3, false),  # qmat observed 2.988
    (3, :Legendre, :RadauRight, :BE, 4, :lastnode, 4, false),  # qmat observed 3.983
    (3, :Legendre, :RadauRight, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (3, :Legendre, :RadauRight, :FE, 2, :quadrature, 3, false),  # qmat observed 2.998
    (3, :Legendre, :RadauRight, :FE, 3, :quadrature, 4, false),  # qmat observed 4.002
    (3, :Legendre, :RadauRight, :FE, 1, :lastnode, 1, false),  # qmat observed 1.033
    (3, :Legendre, :RadauRight, :FE, 2, :lastnode, 2, false),  # qmat observed 2.003
    (3, :Legendre, :RadauRight, :FE, 3, :lastnode, 3, false),  # qmat observed 3.013
    (3, :Legendre, :RadauRight, :FE, 4, :lastnode, 4, false),  # qmat observed 4.061
    (3, :Legendre, :RadauRight, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.996
    (3, :Legendre, :RadauRight, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.039
    (3, :Legendre, :RadauRight, :Trapezoid, 3, :quadrature, 5, false),  # qmat observed 4.956
    (3, :Legendre, :RadauRight, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 1.999
    (3, :Legendre, :RadauRight, :Trapezoid, 2, :lastnode, 4, true),  # qmat observed 3.968
    (3, :Legendre, :RadauRight, :Trapezoid, 3, :lastnode, 5, true),  # qmat observed 4.728
    (3, :Legendre, :RadauRight, :Trapezoid, 4, :lastnode, 5, false),  # qmat observed 4.978
    (3, :Legendre, :RadauRight, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.991
    (3, :Legendre, :RadauRight, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.907
    (3, :Legendre, :RadauRight, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.523
    (3, :Legendre, :RadauRight, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (3, :Legendre, :RadauRight, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.964
    (3, :Legendre, :RadauRight, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.863
    (4, :Legendre, :RadauRight, :BE, 1, :quadrature, 2, false),  # qmat observed 1.997
    (4, :Legendre, :RadauRight, :BE, 2, :quadrature, 3, false),  # qmat observed 2.981
    (4, :Legendre, :RadauRight, :BE, 3, :quadrature, 4, false),  # qmat observed 3.923
    (4, :Legendre, :RadauRight, :BE, 1, :lastnode, 1, false),  # qmat observed 0.975
    (4, :Legendre, :RadauRight, :BE, 2, :lastnode, 2, false),  # qmat observed 1.997
    (4, :Legendre, :RadauRight, :BE, 3, :lastnode, 3, false),  # qmat observed 3.002
    (4, :Legendre, :RadauRight, :BE, 4, :lastnode, 4, false),  # qmat observed 4.057
    (4, :Legendre, :RadauRight, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (4, :Legendre, :RadauRight, :FE, 2, :quadrature, 3, false),  # qmat observed 3.002
    (4, :Legendre, :RadauRight, :FE, 3, :quadrature, 4, false),  # qmat observed 4.018
    (4, :Legendre, :RadauRight, :FE, 1, :lastnode, 1, false),  # qmat observed 1.025
    (4, :Legendre, :RadauRight, :FE, 2, :lastnode, 2, false),  # qmat observed 2.004
    (4, :Legendre, :RadauRight, :FE, 3, :lastnode, 3, false),  # qmat observed 3.020
    (4, :Legendre, :RadauRight, :FE, 4, :lastnode, 4, false),  # qmat observed 4.085
    (4, :Legendre, :RadauRight, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.997
    (4, :Legendre, :RadauRight, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.202
    (4, :Legendre, :RadauRight, :Trapezoid, 3, :quadrature, 5, false),  # qmat observed 5.207
    (4, :Legendre, :RadauRight, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 2.000
    (4, :Legendre, :RadauRight, :Trapezoid, 2, :lastnode, 4, true),  # qmat observed 3.989
    (4, :Legendre, :RadauRight, :Trapezoid, 3, :lastnode, 4, false),  # qmat observed 4.254
    (4, :Legendre, :RadauRight, :Trapezoid, 4, :lastnode, 7, true),  # qmat observed 6.595
    (4, :Legendre, :RadauRight, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.991
    (4, :Legendre, :RadauRight, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.913
    (4, :Legendre, :RadauRight, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.572
    (4, :Legendre, :RadauRight, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (4, :Legendre, :RadauRight, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.964
    (4, :Legendre, :RadauRight, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.861
    (2, :Legendre, :Lobatto, :BE, 1, :quadrature, 2, false),  # qmat observed 1.988
    (2, :Legendre, :Lobatto, :BE, 2, :quadrature, 2, false),  # qmat observed 2.067
    (2, :Legendre, :Lobatto, :BE, 3, :quadrature, 2, false),  # qmat observed 1.980
    (2, :Legendre, :Lobatto, :BE, 1, :lastnode, 1, false),  # qmat observed 0.918
    (2, :Legendre, :Lobatto, :BE, 2, :lastnode, 2, false),  # qmat observed 1.975
    (2, :Legendre, :Lobatto, :BE, 3, :lastnode, 2, false),  # qmat observed 1.930
    (2, :Legendre, :Lobatto, :BE, 4, :lastnode, 2, false),  # qmat observed 2.010
    (2, :Legendre, :Lobatto, :FE, 1, :quadrature, 2, false),  # qmat observed 2.002
    (2, :Legendre, :Lobatto, :FE, 2, :quadrature, 2, false),  # qmat observed 2.004
    (2, :Legendre, :Lobatto, :FE, 3, :quadrature, 2, false),  # qmat observed 2.015
    (2, :Legendre, :Lobatto, :FE, 1, :lastnode, 1, false),  # qmat observed 1.084
    (2, :Legendre, :Lobatto, :FE, 2, :lastnode, 2, false),  # qmat observed 2.002
    (2, :Legendre, :Lobatto, :FE, 3, :lastnode, 2, false),  # qmat observed 2.004
    (2, :Legendre, :Lobatto, :FE, 4, :lastnode, 2, false),  # qmat observed 2.015
    (2, :Legendre, :Lobatto, :Trapezoid, 1, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Legendre, :Lobatto, :Trapezoid, 2, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Legendre, :Lobatto, :Trapezoid, 3, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Legendre, :Lobatto, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 1.996
    (2, :Legendre, :Lobatto, :Trapezoid, 2, :lastnode, 2, false),  # qmat observed 1.996
    (2, :Legendre, :Lobatto, :Trapezoid, 3, :lastnode, 2, false),  # qmat observed 1.996
    (2, :Legendre, :Lobatto, :Trapezoid, 4, :lastnode, 2, false),  # qmat observed 1.996
    (2, :Legendre, :Lobatto, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.988
    (2, :Legendre, :Lobatto, :BEpar, 2, :quadrature, 2, false),  # qmat observed 2.067
    (2, :Legendre, :Lobatto, :BEpar, 3, :quadrature, 2, false),  # qmat observed 1.980
    (2, :Legendre, :Lobatto, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (2, :Legendre, :Lobatto, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.975
    (2, :Legendre, :Lobatto, :BEpar, 3, :lastnode, 2, false),  # qmat observed 1.930
    (2, :Legendre, :Lobatto, :BEpar, 4, :lastnode, 2, false),  # qmat observed 2.010
    (3, :Legendre, :Lobatto, :BE, 1, :quadrature, 2, false),  # qmat observed 1.995
    (3, :Legendre, :Lobatto, :BE, 2, :quadrature, 3, false),  # qmat observed 2.963
    (3, :Legendre, :Lobatto, :BE, 3, :quadrature, 4, false),  # qmat observed 3.898
    (3, :Legendre, :Lobatto, :BE, 1, :lastnode, 1, false),  # qmat observed 0.959
    (3, :Legendre, :Lobatto, :BE, 2, :lastnode, 2, false),  # qmat observed 1.992
    (3, :Legendre, :Lobatto, :BE, 3, :lastnode, 3, false),  # qmat observed 2.968
    (3, :Legendre, :Lobatto, :BE, 4, :lastnode, 4, false),  # qmat observed 3.655
    (3, :Legendre, :Lobatto, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (3, :Legendre, :Lobatto, :FE, 2, :quadrature, 3, false),  # qmat observed 2.996
    (3, :Legendre, :Lobatto, :FE, 3, :quadrature, 4, false),  # qmat observed 3.998
    (3, :Legendre, :Lobatto, :FE, 1, :lastnode, 1, false),  # qmat observed 1.042
    (3, :Legendre, :Lobatto, :FE, 2, :lastnode, 2, false),  # qmat observed 2.004
    (3, :Legendre, :Lobatto, :FE, 3, :lastnode, 3, false),  # qmat observed 3.025
    (3, :Legendre, :Lobatto, :FE, 4, :lastnode, 4, false),  # qmat observed 4.096
    (3, :Legendre, :Lobatto, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.995
    (3, :Legendre, :Lobatto, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 3.959
    (3, :Legendre, :Lobatto, :Trapezoid, 3, :quadrature, 4, false),  # qmat observed 3.974
    (3, :Legendre, :Lobatto, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 1.999
    (3, :Legendre, :Lobatto, :Trapezoid, 2, :lastnode, 4, true),  # qmat observed 3.956
    (3, :Legendre, :Lobatto, :Trapezoid, 3, :lastnode, 4, false),  # qmat observed 3.976
    (3, :Legendre, :Lobatto, :Trapezoid, 4, :lastnode, 4, false),  # qmat observed 3.975
    (3, :Legendre, :Lobatto, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.990
    (3, :Legendre, :Lobatto, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.898
    (3, :Legendre, :Lobatto, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.530
    (3, :Legendre, :Lobatto, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (3, :Legendre, :Lobatto, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.964
    (3, :Legendre, :Lobatto, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.866
    (4, :Legendre, :Lobatto, :BE, 1, :quadrature, 2, false),  # qmat observed 1.996
    (4, :Legendre, :Lobatto, :BE, 2, :quadrature, 3, false),  # qmat observed 2.976
    (4, :Legendre, :Lobatto, :BE, 3, :quadrature, 4, false),  # qmat observed 3.897
    (4, :Legendre, :Lobatto, :BE, 1, :lastnode, 1, false),  # qmat observed 0.971
    (4, :Legendre, :Lobatto, :BE, 2, :lastnode, 2, false),  # qmat observed 1.996
    (4, :Legendre, :Lobatto, :BE, 3, :lastnode, 3, false),  # qmat observed 2.996
    (4, :Legendre, :Lobatto, :BE, 4, :lastnode, 4, false),  # qmat observed 4.027
    (4, :Legendre, :Lobatto, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (4, :Legendre, :Lobatto, :FE, 2, :quadrature, 3, false),  # qmat observed 3.002
    (4, :Legendre, :Lobatto, :FE, 3, :quadrature, 4, false),  # qmat observed 4.024
    (4, :Legendre, :Lobatto, :FE, 1, :lastnode, 1, false),  # qmat observed 1.029
    (4, :Legendre, :Lobatto, :FE, 2, :lastnode, 2, false),  # qmat observed 2.004
    (4, :Legendre, :Lobatto, :FE, 3, :lastnode, 3, false),  # qmat observed 3.018
    (4, :Legendre, :Lobatto, :FE, 4, :lastnode, 4, false),  # qmat observed 4.078
    (4, :Legendre, :Lobatto, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.996
    (4, :Legendre, :Lobatto, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.176
    (4, :Legendre, :Lobatto, :Trapezoid, 3, :quadrature, 5, false),  # qmat observed 5.444
    (4, :Legendre, :Lobatto, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 1.999
    (4, :Legendre, :Lobatto, :Trapezoid, 2, :lastnode, 4, true),  # qmat observed 3.987
    (4, :Legendre, :Lobatto, :Trapezoid, 3, :lastnode, 4, false),  # qmat observed 4.375
    (4, :Legendre, :Lobatto, :Trapezoid, 4, :lastnode, 6, true),  # qmat observed 5.937
    (4, :Legendre, :Lobatto, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.991
    (4, :Legendre, :Lobatto, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.914
    (4, :Legendre, :Lobatto, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.563
    (4, :Legendre, :Lobatto, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (4, :Legendre, :Lobatto, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.964
    (4, :Legendre, :Lobatto, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.861
    (2, :Equidistant, :Gauss, :BE, 1, :quadrature, 2, false),  # qmat observed 1.997
    (2, :Equidistant, :Gauss, :BE, 2, :quadrature, 2, false),  # qmat observed 1.992
    (2, :Equidistant, :Gauss, :BE, 3, :quadrature, 2, false),  # qmat observed 1.999
    (2, :Equidistant, :Gauss, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (2, :Equidistant, :Gauss, :FE, 2, :quadrature, 2, false),  # qmat observed 2.018
    (2, :Equidistant, :Gauss, :FE, 3, :quadrature, 2, false),  # qmat observed 1.995
    (2, :Equidistant, :Gauss, :Trapezoid, 1, :quadrature, 2, false),  # qmat observed 2.000
    (2, :Equidistant, :Gauss, :Trapezoid, 2, :quadrature, 2, false),  # qmat observed 2.000
    (2, :Equidistant, :Gauss, :Trapezoid, 3, :quadrature, 2, false),  # qmat observed 1.997
    (2, :Equidistant, :Gauss, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.994
    (2, :Equidistant, :Gauss, :BEpar, 2, :quadrature, 2, false),  # qmat observed 2.019
    (2, :Equidistant, :Gauss, :BEpar, 3, :quadrature, 2, false),  # qmat observed 2.027
    (3, :Equidistant, :Gauss, :BE, 1, :quadrature, 2, false),  # qmat observed 1.998
    (3, :Equidistant, :Gauss, :BE, 2, :quadrature, 3, false),  # qmat observed 2.990
    (3, :Equidistant, :Gauss, :BE, 3, :quadrature, 4, false),  # qmat observed 3.948
    (3, :Equidistant, :Gauss, :FE, 1, :quadrature, 2, false),  # qmat observed 2.000
    (3, :Equidistant, :Gauss, :FE, 2, :quadrature, 3, false),  # qmat observed 2.996
    (3, :Equidistant, :Gauss, :FE, 3, :quadrature, 4, false),  # qmat observed 4.396
    (3, :Equidistant, :Gauss, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.995
    (3, :Equidistant, :Gauss, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 3.968
    (3, :Equidistant, :Gauss, :Trapezoid, 3, :quadrature, 4, false),  # qmat observed 3.992
    (3, :Equidistant, :Gauss, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.992
    (3, :Equidistant, :Gauss, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.929
    (3, :Equidistant, :Gauss, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.660
    (4, :Equidistant, :Gauss, :BE, 1, :quadrature, 2, false),  # qmat observed 1.998
    (4, :Equidistant, :Gauss, :BE, 2, :quadrature, 3, false),  # qmat observed 2.992
    (4, :Equidistant, :Gauss, :BE, 3, :quadrature, 4, false),  # qmat observed 4.122
    (4, :Equidistant, :Gauss, :FE, 1, :quadrature, 2, false),  # qmat observed 2.000
    (4, :Equidistant, :Gauss, :FE, 2, :quadrature, 3, false),  # qmat observed 3.001
    (4, :Equidistant, :Gauss, :FE, 3, :quadrature, 4, false),  # qmat observed 4.009
    (4, :Equidistant, :Gauss, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.995
    (4, :Equidistant, :Gauss, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 3.986
    (4, :Equidistant, :Gauss, :Trapezoid, 3, :quadrature, 4, false),  # qmat observed 3.953
    (4, :Equidistant, :Gauss, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.992
    (4, :Equidistant, :Gauss, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.922
    (4, :Equidistant, :Gauss, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.618
    (2, :Equidistant, :RadauLeft, :BE, 1, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :RadauLeft, :BE, 2, :quadrature, 2, false),  # qmat observed 1.988
    (2, :Equidistant, :RadauLeft, :BE, 3, :quadrature, 2, false),  # qmat observed 2.006
    (2, :Equidistant, :RadauLeft, :FE, 1, :quadrature, 2, false),  # qmat observed 2.002
    (2, :Equidistant, :RadauLeft, :FE, 2, :quadrature, 2, false),  # qmat observed 2.008
    (2, :Equidistant, :RadauLeft, :FE, 3, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :RadauLeft, :Trapezoid, 1, :quadrature, 2, false),  # qmat observed 2.001
    (2, :Equidistant, :RadauLeft, :Trapezoid, 2, :quadrature, 2, false),  # qmat observed 2.001
    (2, :Equidistant, :RadauLeft, :Trapezoid, 3, :quadrature, 2, false),  # qmat observed 2.001
    (2, :Equidistant, :RadauLeft, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :RadauLeft, :BEpar, 2, :quadrature, 2, false),  # qmat observed 1.988
    (2, :Equidistant, :RadauLeft, :BEpar, 3, :quadrature, 2, false),  # qmat observed 2.006
    (3, :Equidistant, :RadauLeft, :BE, 1, :quadrature, 2, false),  # qmat observed 1.997
    (3, :Equidistant, :RadauLeft, :BE, 2, :quadrature, 3, false),  # qmat observed 2.978
    (3, :Equidistant, :RadauLeft, :BE, 3, :quadrature, 3, false),  # qmat observed 3.077
    (3, :Equidistant, :RadauLeft, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (3, :Equidistant, :RadauLeft, :FE, 2, :quadrature, 3, false),  # qmat observed 3.002
    (3, :Equidistant, :RadauLeft, :FE, 3, :quadrature, 3, false),  # qmat observed 3.007
    (3, :Equidistant, :RadauLeft, :Trapezoid, 1, :quadrature, 4, true),  # qmat observed 3.987
    (3, :Equidistant, :RadauLeft, :Trapezoid, 2, :quadrature, 3, false),  # qmat observed 2.994
    (3, :Equidistant, :RadauLeft, :Trapezoid, 3, :quadrature, 3, false),  # qmat observed 2.995
    (3, :Equidistant, :RadauLeft, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.994
    (3, :Equidistant, :RadauLeft, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.942
    (3, :Equidistant, :RadauLeft, :BEpar, 3, :quadrature, 4, true),  # qmat observed 3.637
    (4, :Equidistant, :RadauLeft, :BE, 1, :quadrature, 2, false),  # qmat observed 1.998
    (4, :Equidistant, :RadauLeft, :BE, 2, :quadrature, 3, false),  # qmat observed 2.992
    (4, :Equidistant, :RadauLeft, :BE, 3, :quadrature, 4, false),  # qmat observed 4.169
    (4, :Equidistant, :RadauLeft, :FE, 1, :quadrature, 2, false),  # qmat observed 2.000
    (4, :Equidistant, :RadauLeft, :FE, 2, :quadrature, 3, false),  # qmat observed 3.003
    (4, :Equidistant, :RadauLeft, :FE, 3, :quadrature, 4, false),  # qmat observed 4.015
    (4, :Equidistant, :RadauLeft, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.995
    (4, :Equidistant, :RadauLeft, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 3.989
    (4, :Equidistant, :RadauLeft, :Trapezoid, 3, :quadrature, 4, false),  # qmat observed 4.004
    (4, :Equidistant, :RadauLeft, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.992
    (4, :Equidistant, :RadauLeft, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.931
    (4, :Equidistant, :RadauLeft, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.677
    (2, :Equidistant, :RadauRight, :BE, 1, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :RadauRight, :BE, 2, :quadrature, 2, false),  # qmat observed 1.997
    (2, :Equidistant, :RadauRight, :BE, 3, :quadrature, 2, false),  # qmat observed 2.004
    (2, :Equidistant, :RadauRight, :BE, 1, :lastnode, 1, false),  # qmat observed 0.959
    (2, :Equidistant, :RadauRight, :BE, 2, :lastnode, 2, false),  # qmat observed 1.989
    (2, :Equidistant, :RadauRight, :BE, 3, :lastnode, 2, false),  # qmat observed 2.018
    (2, :Equidistant, :RadauRight, :BE, 4, :lastnode, 2, false),  # qmat observed 1.998
    (2, :Equidistant, :RadauRight, :FE, 1, :quadrature, 2, false),  # qmat observed 2.002
    (2, :Equidistant, :RadauRight, :FE, 2, :quadrature, 2, false),  # qmat observed 2.067
    (2, :Equidistant, :RadauRight, :FE, 3, :quadrature, 2, false),  # qmat observed 1.997
    (2, :Equidistant, :RadauRight, :FE, 1, :lastnode, 1, false),  # qmat observed 1.042
    (2, :Equidistant, :RadauRight, :FE, 2, :lastnode, 2, false),  # qmat observed 2.005
    (2, :Equidistant, :RadauRight, :FE, 3, :lastnode, 2, false),  # qmat observed 2.032
    (2, :Equidistant, :RadauRight, :FE, 4, :lastnode, 2, false),  # qmat observed 1.998
    (2, :Equidistant, :RadauRight, :Trapezoid, 1, :quadrature, 2, false),  # qmat observed 2.001
    (2, :Equidistant, :RadauRight, :Trapezoid, 2, :quadrature, 2, false),  # qmat observed 2.010
    (2, :Equidistant, :RadauRight, :Trapezoid, 3, :quadrature, 2, false),  # qmat observed 2.000
    (2, :Equidistant, :RadauRight, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 1.999
    (2, :Equidistant, :RadauRight, :Trapezoid, 2, :lastnode, 2, false),  # qmat observed 1.997
    (2, :Equidistant, :RadauRight, :Trapezoid, 3, :lastnode, 2, false),  # qmat observed 2.002
    (2, :Equidistant, :RadauRight, :Trapezoid, 4, :lastnode, 2, false),  # qmat observed 2.000
    (2, :Equidistant, :RadauRight, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :RadauRight, :BEpar, 2, :quadrature, 2, false),  # qmat observed 2.023
    (2, :Equidistant, :RadauRight, :BEpar, 3, :quadrature, 2, false),  # qmat observed 2.038
    (2, :Equidistant, :RadauRight, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (2, :Equidistant, :RadauRight, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.962
    (2, :Equidistant, :RadauRight, :BEpar, 3, :lastnode, 2, false),  # qmat observed 2.407
    (2, :Equidistant, :RadauRight, :BEpar, 4, :lastnode, 2, false),  # qmat observed 1.907
    (3, :Equidistant, :RadauRight, :BE, 1, :quadrature, 2, false),  # qmat observed 1.997
    (3, :Equidistant, :RadauRight, :BE, 2, :quadrature, 3, false),  # qmat observed 2.990
    (3, :Equidistant, :RadauRight, :BE, 3, :quadrature, 3, false),  # qmat observed 2.976
    (3, :Equidistant, :RadauRight, :BE, 1, :lastnode, 1, false),  # qmat observed 0.972
    (3, :Equidistant, :RadauRight, :BE, 2, :lastnode, 2, false),  # qmat observed 1.998
    (3, :Equidistant, :RadauRight, :BE, 3, :lastnode, 3, false),  # qmat observed 2.988
    (3, :Equidistant, :RadauRight, :BE, 4, :lastnode, 3, false),  # qmat observed 3.031
    (3, :Equidistant, :RadauRight, :FE, 1, :quadrature, 2, false),  # qmat observed 2.000
    (3, :Equidistant, :RadauRight, :FE, 2, :quadrature, 3, false),  # qmat observed 2.991
    (3, :Equidistant, :RadauRight, :FE, 3, :quadrature, 3, false),  # qmat observed 2.960
    (3, :Equidistant, :RadauRight, :FE, 1, :lastnode, 1, false),  # qmat observed 1.028
    (3, :Equidistant, :RadauRight, :FE, 2, :lastnode, 2, false),  # qmat observed 2.004
    (3, :Equidistant, :RadauRight, :FE, 3, :lastnode, 4, true),  # qmat observed 4.144
    (3, :Equidistant, :RadauRight, :FE, 4, :lastnode, 3, false),  # qmat observed 2.993
    (3, :Equidistant, :RadauRight, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.996
    (3, :Equidistant, :RadauRight, :Trapezoid, 2, :quadrature, 3, false),  # qmat observed 3.019
    (3, :Equidistant, :RadauRight, :Trapezoid, 3, :quadrature, 3, false),  # qmat observed 2.997
    (3, :Equidistant, :RadauRight, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 2.000
    (3, :Equidistant, :RadauRight, :Trapezoid, 2, :lastnode, 3, false),  # qmat observed 2.994
    (3, :Equidistant, :RadauRight, :Trapezoid, 3, :lastnode, 3, false),  # qmat observed 3.000
    (3, :Equidistant, :RadauRight, :Trapezoid, 4, :lastnode, 3, false),  # qmat observed 2.996
    (3, :Equidistant, :RadauRight, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.988
    (3, :Equidistant, :RadauRight, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.890
    (3, :Equidistant, :RadauRight, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (3, :Equidistant, :RadauRight, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.965
    (3, :Equidistant, :RadauRight, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.868
    (4, :Equidistant, :RadauRight, :BE, 1, :quadrature, 2, false),  # qmat observed 1.998
    (4, :Equidistant, :RadauRight, :BE, 2, :quadrature, 3, false),  # qmat observed 2.987
    (4, :Equidistant, :RadauRight, :BE, 3, :quadrature, 4, false),  # qmat observed 3.961
    (4, :Equidistant, :RadauRight, :BE, 1, :lastnode, 1, false),  # qmat observed 0.979
    (4, :Equidistant, :RadauRight, :BE, 2, :lastnode, 2, false),  # qmat observed 1.999
    (4, :Equidistant, :RadauRight, :BE, 3, :lastnode, 3, false),  # qmat observed 3.001
    (4, :Equidistant, :RadauRight, :BE, 4, :lastnode, 4, false),  # qmat observed 3.934
    (4, :Equidistant, :RadauRight, :FE, 1, :quadrature, 2, false),  # qmat observed 2.000
    (4, :Equidistant, :RadauRight, :FE, 2, :quadrature, 3, false),  # qmat observed 2.998
    (4, :Equidistant, :RadauRight, :FE, 3, :quadrature, 4, false),  # qmat observed 4.000
    (4, :Equidistant, :RadauRight, :FE, 1, :lastnode, 1, false),  # qmat observed 1.021
    (4, :Equidistant, :RadauRight, :FE, 2, :lastnode, 2, false),  # qmat observed 2.004
    (4, :Equidistant, :RadauRight, :FE, 3, :lastnode, 3, false),  # qmat observed 3.033
    (4, :Equidistant, :RadauRight, :FE, 4, :lastnode, 4, false),  # qmat observed 4.099
    (4, :Equidistant, :RadauRight, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.995
    (4, :Equidistant, :RadauRight, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.086
    (4, :Equidistant, :RadauRight, :Trapezoid, 3, :quadrature, 4, false),  # qmat observed 4.011
    (4, :Equidistant, :RadauRight, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 2.000
    (4, :Equidistant, :RadauRight, :Trapezoid, 2, :lastnode, 4, true),  # qmat observed 3.991
    (4, :Equidistant, :RadauRight, :Trapezoid, 3, :lastnode, 4, false),  # qmat observed 4.015
    (4, :Equidistant, :RadauRight, :Trapezoid, 4, :lastnode, 4, false),  # qmat observed 4.005
    (4, :Equidistant, :RadauRight, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.992
    (4, :Equidistant, :RadauRight, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.921
    (4, :Equidistant, :RadauRight, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.588
    (4, :Equidistant, :RadauRight, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (4, :Equidistant, :RadauRight, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.963
    (4, :Equidistant, :RadauRight, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.857
    (2, :Equidistant, :Lobatto, :BE, 1, :quadrature, 2, false),  # qmat observed 1.988
    (2, :Equidistant, :Lobatto, :BE, 2, :quadrature, 2, false),  # qmat observed 2.067
    (2, :Equidistant, :Lobatto, :BE, 3, :quadrature, 2, false),  # qmat observed 1.980
    (2, :Equidistant, :Lobatto, :BE, 1, :lastnode, 1, false),  # qmat observed 0.918
    (2, :Equidistant, :Lobatto, :BE, 2, :lastnode, 2, false),  # qmat observed 1.975
    (2, :Equidistant, :Lobatto, :BE, 3, :lastnode, 2, false),  # qmat observed 1.930
    (2, :Equidistant, :Lobatto, :BE, 4, :lastnode, 2, false),  # qmat observed 2.010
    (2, :Equidistant, :Lobatto, :FE, 1, :quadrature, 2, false),  # qmat observed 2.002
    (2, :Equidistant, :Lobatto, :FE, 2, :quadrature, 2, false),  # qmat observed 2.004
    (2, :Equidistant, :Lobatto, :FE, 3, :quadrature, 2, false),  # qmat observed 2.015
    (2, :Equidistant, :Lobatto, :FE, 1, :lastnode, 1, false),  # qmat observed 1.084
    (2, :Equidistant, :Lobatto, :FE, 2, :lastnode, 2, false),  # qmat observed 2.002
    (2, :Equidistant, :Lobatto, :FE, 3, :lastnode, 2, false),  # qmat observed 2.004
    (2, :Equidistant, :Lobatto, :FE, 4, :lastnode, 2, false),  # qmat observed 2.015
    (2, :Equidistant, :Lobatto, :Trapezoid, 1, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :Lobatto, :Trapezoid, 2, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :Lobatto, :Trapezoid, 3, :quadrature, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :Lobatto, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :Lobatto, :Trapezoid, 2, :lastnode, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :Lobatto, :Trapezoid, 3, :lastnode, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :Lobatto, :Trapezoid, 4, :lastnode, 2, false),  # qmat observed 1.996
    (2, :Equidistant, :Lobatto, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.988
    (2, :Equidistant, :Lobatto, :BEpar, 2, :quadrature, 2, false),  # qmat observed 2.067
    (2, :Equidistant, :Lobatto, :BEpar, 3, :quadrature, 2, false),  # qmat observed 1.980
    (2, :Equidistant, :Lobatto, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (2, :Equidistant, :Lobatto, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.975
    (2, :Equidistant, :Lobatto, :BEpar, 3, :lastnode, 2, false),  # qmat observed 1.930
    (2, :Equidistant, :Lobatto, :BEpar, 4, :lastnode, 2, false),  # qmat observed 2.010
    (3, :Equidistant, :Lobatto, :BE, 1, :quadrature, 2, false),  # qmat observed 1.995
    (3, :Equidistant, :Lobatto, :BE, 2, :quadrature, 3, false),  # qmat observed 2.963
    (3, :Equidistant, :Lobatto, :BE, 3, :quadrature, 4, false),  # qmat observed 3.898
    (3, :Equidistant, :Lobatto, :BE, 1, :lastnode, 1, false),  # qmat observed 0.959
    (3, :Equidistant, :Lobatto, :BE, 2, :lastnode, 2, false),  # qmat observed 1.992
    (3, :Equidistant, :Lobatto, :BE, 3, :lastnode, 3, false),  # qmat observed 2.968
    (3, :Equidistant, :Lobatto, :BE, 4, :lastnode, 4, false),  # qmat observed 3.655
    (3, :Equidistant, :Lobatto, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (3, :Equidistant, :Lobatto, :FE, 2, :quadrature, 3, false),  # qmat observed 2.996
    (3, :Equidistant, :Lobatto, :FE, 3, :quadrature, 4, false),  # qmat observed 3.998
    (3, :Equidistant, :Lobatto, :FE, 1, :lastnode, 1, false),  # qmat observed 1.042
    (3, :Equidistant, :Lobatto, :FE, 2, :lastnode, 2, false),  # qmat observed 2.004
    (3, :Equidistant, :Lobatto, :FE, 3, :lastnode, 3, false),  # qmat observed 3.025
    (3, :Equidistant, :Lobatto, :FE, 4, :lastnode, 4, false),  # qmat observed 4.096
    (3, :Equidistant, :Lobatto, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.995
    (3, :Equidistant, :Lobatto, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 3.959
    (3, :Equidistant, :Lobatto, :Trapezoid, 3, :quadrature, 4, false),  # qmat observed 3.974
    (3, :Equidistant, :Lobatto, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 1.999
    (3, :Equidistant, :Lobatto, :Trapezoid, 2, :lastnode, 4, true),  # qmat observed 3.956
    (3, :Equidistant, :Lobatto, :Trapezoid, 3, :lastnode, 4, false),  # qmat observed 3.976
    (3, :Equidistant, :Lobatto, :Trapezoid, 4, :lastnode, 4, false),  # qmat observed 3.975
    (3, :Equidistant, :Lobatto, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.990
    (3, :Equidistant, :Lobatto, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.898
    (3, :Equidistant, :Lobatto, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.530
    (3, :Equidistant, :Lobatto, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (3, :Equidistant, :Lobatto, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.964
    (3, :Equidistant, :Lobatto, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.866
    (4, :Equidistant, :Lobatto, :BE, 1, :quadrature, 2, false),  # qmat observed 1.997
    (4, :Equidistant, :Lobatto, :BE, 2, :quadrature, 3, false),  # qmat observed 2.980
    (4, :Equidistant, :Lobatto, :BE, 3, :quadrature, 4, false),  # qmat observed 3.918
    (4, :Equidistant, :Lobatto, :BE, 1, :lastnode, 1, false),  # qmat observed 0.972
    (4, :Equidistant, :Lobatto, :BE, 2, :lastnode, 2, false),  # qmat observed 1.997
    (4, :Equidistant, :Lobatto, :BE, 3, :lastnode, 3, false),  # qmat observed 3.012
    (4, :Equidistant, :Lobatto, :BE, 4, :lastnode, 4, false),  # qmat observed 4.266
    (4, :Equidistant, :Lobatto, :FE, 1, :quadrature, 2, false),  # qmat observed 2.001
    (4, :Equidistant, :Lobatto, :FE, 2, :quadrature, 3, false),  # qmat observed 3.001
    (4, :Equidistant, :Lobatto, :FE, 3, :quadrature, 4, false),  # qmat observed 4.015
    (4, :Equidistant, :Lobatto, :FE, 1, :lastnode, 1, false),  # qmat observed 1.028
    (4, :Equidistant, :Lobatto, :FE, 2, :lastnode, 2, false),  # qmat observed 2.005
    (4, :Equidistant, :Lobatto, :FE, 3, :lastnode, 3, false),  # qmat observed 3.033
    (4, :Equidistant, :Lobatto, :FE, 4, :lastnode, 4, false),  # qmat observed 4.204
    (4, :Equidistant, :Lobatto, :Trapezoid, 1, :quadrature, 3, false),  # qmat observed 2.997
    (4, :Equidistant, :Lobatto, :Trapezoid, 2, :quadrature, 4, false),  # qmat observed 4.000
    (4, :Equidistant, :Lobatto, :Trapezoid, 3, :quadrature, 4, false),  # qmat observed 3.953
    (4, :Equidistant, :Lobatto, :Trapezoid, 1, :lastnode, 2, false),  # qmat observed 2.000
    (4, :Equidistant, :Lobatto, :Trapezoid, 2, :lastnode, 5, true),  # qmat observed 4.525
    (4, :Equidistant, :Lobatto, :Trapezoid, 3, :lastnode, 4, false),  # qmat observed 3.944
    (4, :Equidistant, :Lobatto, :Trapezoid, 4, :lastnode, 4, false),  # qmat observed 3.952
    (4, :Equidistant, :Lobatto, :BEpar, 1, :quadrature, 2, false),  # qmat observed 1.991
    (4, :Equidistant, :Lobatto, :BEpar, 2, :quadrature, 3, false),  # qmat observed 2.907
    (4, :Equidistant, :Lobatto, :BEpar, 3, :quadrature, 4, false),  # qmat observed 3.534
    (4, :Equidistant, :Lobatto, :BEpar, 1, :lastnode, 1, false),  # qmat observed 0.918
    (4, :Equidistant, :Lobatto, :BEpar, 2, :lastnode, 2, false),  # qmat observed 1.964
    (4, :Equidistant, :Lobatto, :BEpar, 3, :lastnode, 3, false),  # qmat observed 2.864
]
# rows: 470, of which bonus cases: 13
